# Unimind Studios — site copy (DRAFT, written for you to edit).
# Plain English, short sentences. Nothing here claims a client, a number or a result.
# Edit freely, then run:  python3 build.py

SERVICES = [
 {
  "slug": "brand-identity",
  "name": "Brand identity",
  "menu": "Name, logo, colours and voice",
  "line": "A name, logo, colour palette and tone of voice that make you easy to recognise and remember.",
  "title": "Brand Identity Design | Logo, Colours and Voice | Unimind",
  "desc": "Brand identity design from Unimind Studios: a logo, colours, fonts and tone of voice that make your business easy to recognise, plus simple rules to use them.",
  "h1": "A brand people recognise at a glance.",
  "lede": "We design how your business looks and sounds, then write it down in a short guide so everyone who works with you keeps it consistent.",
  "q": "What is brand identity?",
  "a": "Brand identity is everything that makes your business recognisable: your logo, colours, fonts, images and the way you write. A good identity looks the same on your website, your invoices and your social posts, so people remember you and trust you sooner.",
  "ch_h": "Why most brands feel patchy.",
  "ch_p": "A logo made in a hurry, a website in different colours, social posts in a third style. Customers notice, even when they can't say why.",
  "ch": ["Your logo looks blurry or cramped on phones", "Every designer uses different colours and fonts", "Your writing changes tone from page to page", "You look smaller or older than you really are"],
  "ov_h": "One clear system instead of loose pieces.",
  "ov_p": "We start by understanding who your customers are and how you want them to feel. Then we design a small set of parts that work together and write simple rules for using them.",
  "ov_note": "The goal is not a fancy logo. It is a brand your team can use correctly without asking us every time.",
  "benefits": ["People recognise you faster", "New materials take less time to make", "Your business looks as established as it is", "Designers and printers get clear instructions"],
  "deliver": ["Short brand questionnaire and workshop", "Logo in full, short and icon versions", "Colour palette with print and screen codes", "Font choices for headings and text", "Tone of voice guide with examples", "Business card and letterhead design", "Social media profile and post templates", "Brand guidelines document", "All files in the formats you need"],
  "uses": ["Launching a new business", "Refreshing a dated logo", "Merging two companies into one brand", "Preparing for a new website", "Entering a new market", "Creating a sub-brand for a new product"],
  "steps": [["Discover", "A workshop about your customers, competitors and the impression you want to make."], ["Explore", "Two or three different directions, shown on real examples like a website header and a business card."], ["Refine", "We develop the direction you choose and test it at small and large sizes."], ["Hand over", "Final files plus a guide that explains how to use everything."]],
  "tools": [["Design", ["Figma", "Adobe Illustrator"]], ["Images", ["Adobe Photoshop"]], ["Guides", ["Figma", "PDF"]]],
  "faq": [["Do you only design logos?", "No. A logo is one part of a brand. We also choose colours and fonts, set the tone of voice and give you templates, so the logo is used well."], ["Can you keep parts of our current brand?", "Yes. If people already know your logo or colours, we can modernise them instead of starting over. We discuss this in the first workshop."], ["Will we own the logo?", "You will own the final logo and brand files once the project is paid in full. The exact terms are written in our agreement."]],
  "related": ["website-design", "seo-content", "ux-product-design"],
  "cta_h": "Start with a brand workshop.",
  "cta_p": "Tell us what your business does and who it serves. We'll explain what a brand project would include for you.",
 },
 {
  "slug": "website-design",
  "name": "Website design",
  "menu": "Pages laid out around your customer",
  "line": "Page layouts planned around your customer's questions, shown to you as clickable drafts before any code.",
  "title": "Website Design Services | Customer-First Pages | Unimind",
  "desc": "Website design from Unimind Studios: page plans and layouts built around your customers' questions, shown as clickable drafts before any code is written.",
  "h1": "Website design that answers your customer first.",
  "lede": "We plan every page around the questions your customers ask, then design layouts you can click through and comment on before anything is built.",
  "q": "What is website design?",
  "a": "Website design is planning what goes on each page and how it looks: the order of information, the headings, the images and the buttons. Good design makes it obvious what you do and what the visitor should do next, on a phone as well as a laptop.",
  "ch_h": "Why good businesses get weak websites.",
  "ch_p": "Many sites are designed around the company's org chart instead of the customer's questions. The result looks fine but doesn't help anyone decide.",
  "ch": ["The first screen doesn't say what you do", "Important pages are hard to find in the menu", "The site looks cramped or broken on phones", "Visitors read but don't contact you"],
  "ov_h": "Words first, then layout, then style.",
  "ov_p": "We write the key messages and map the pages before we pick colours. That way the design supports what you need to say, instead of decorating empty boxes.",
  "ov_note": "You see clickable drafts early, so changes happen while they are cheap, not after the site is built.",
  "benefits": ["Visitors understand you in seconds", "Clear next steps on every page", "Layouts that work on any screen", "Fewer surprises during the build"],
  "deliver": ["Review of your current site and competitors", "Site map showing every page", "Key messages for each page", "Wireframes (simple page sketches)", "Full visual design for every page type", "Mobile and desktop versions", "Clickable prototype for review", "Design system of buttons, forms and cards", "Hand-over files for developers"],
  "uses": ["A first website for a new business", "Redesigning a confusing old site", "A landing page for a campaign", "Adding a new section or product range", "Preparing a site for search engines", "Making a site easier to use on phones"],
  "steps": [["Plan", "We agree who the site is for, what each page must do and how it will be measured."], ["Sketch", "Simple wireframes show the order of content without colours or images."], ["Design", "We apply your brand and design each page type for mobile and desktop."], ["Review", "You click through the prototype and leave comments directly on it."], ["Prepare", "Final designs are organised so the build goes smoothly."]],
  "tools": [["Design", ["Figma"]], ["Review", ["Figma prototypes", "Comments"]], ["Content", ["Google Docs"]]],
  "faq": [["Do we need to write all the text ourselves?", "No. We draft the key messages from what you tell us, and you correct anything that isn't right. You know your business, we know how to make it clear."], ["Can you design a site we build ourselves?", "Yes. We can hand over organised design files that your own developer can build from."], ["How many changes can we ask for?", "The number of review rounds is agreed in the quote. Most changes happen during the wireframe stage, when they take the least time."]],
  "related": ["website-development", "brand-identity", "seo-content"],
  "cta_h": "See your site before it's built.",
  "cta_p": "Tell us about your business and current website. We'll suggest a page plan and the next step.",
 },
 {
  "slug": "website-development",
  "name": "Website development",
  "menu": "Fast, accessible code you own",
  "line": "We turn the approved design into a fast, accessible website that works on every screen size.",
  "title": "Website Development | Fast, Accessible Websites | Unimind",
  "desc": "Website development from Unimind Studios: fast, accessible websites built from approved designs, easy for your team to edit, with files and logins handed over",
  "h1": "Websites built to load fast and last.",
  "lede": "We turn approved designs into a working website that loads quickly, works on every screen and lets your team edit pages without calling a developer.",
  "q": "What is website development?",
  "a": "Website development is building the actual working site from the design. It covers the code, the editing system your team uses, the forms, the hosting and the checks that make sure every page works on phones, tablets and computers.",
  "ch_h": "Why websites slow down and break.",
  "ch_p": "Heavy themes, too many plug-ins and rushed code make sites slow and fragile. Small edits start to feel risky.",
  "ch": ["Pages take several seconds to appear", "Updates break layouts or forms", "Only one person knows how the site works", "The site fails basic accessibility checks"],
  "ov_h": "Simple, tidy builds your team can live with.",
  "ov_p": "We pick the lightest setup that does the job. Sometimes that is WordPress or Shopify so your team can edit easily, sometimes plain hand-written code for speed.",
  "ov_note": "Accessibility means people using screen readers or keyboards can use your site too. We build it in from the start.",
  "benefits": ["Faster pages on real phones", "Easy editing for your team", "Fewer things that can break", "You own the files and logins"],
  "deliver": ["Build of every designed page", "Content management setup (CMS)", "Contact and newsletter forms", "Speed and image optimisation", "Accessibility checks", "Search basics: titles, descriptions, sitemap", "Analytics and consent setup", "Testing on phones, tablets and desktops", "Launch and domain connection", "Editing training for your team"],
  "uses": ["Building a newly designed site", "Moving from a slow theme to a lighter build", "Setting up an online shop", "Moving a site to new hosting", "Adding booking or enquiry forms", "Fixing a site that fails speed checks"],
  "steps": [["Set up", "We choose the platform, prepare hosting and set up a private preview site."], ["Build", "Pages, forms and editing tools are built from the approved designs."], ["Test", "We check speed, accessibility, forms and every page on many devices."], ["Launch", "We connect your domain, put the site live and check everything again."], ["Train", "A short session shows your team how to edit pages safely."]],
  "tools": [["Platforms", ["WordPress", "Shopify", "Webflow"]], ["Code", ["HTML", "CSS", "JavaScript"]], ["Checks", ["Lighthouse", "Search Console"]]],
  "faq": [["Which platform will you use?", "It depends on who will edit the site and how often. We explain the options in plain terms and recommend one before the build starts."], ["Can you move our existing content?", "Yes. We can move your pages, posts and images to the new site and set up redirects so old links still work."], ["Do you host websites?", "We help you choose hosting in your own name, so you stay in control. If you prefer, we can manage it for you under a care plan."]],
  "related": ["website-design", "website-care", "seo-content"],
  "cta_h": "Get a faster, tidier website.",
  "cta_p": "Send us your current site or designs. We'll tell you which build approach fits and why.",
 },
 {
  "slug": "ux-product-design",
  "name": "UX and product design",
  "menu": "Apps and tools people can figure out",
  "line": "UX means user experience: how easy your app or tool is to use. We test screens with real people and fix what confuses them.",
  "title": "UX and Product Design | Apps People Can Use | Unimind",
  "desc": "UX and product design from Unimind Studios: research, screen design and testing with real people, so your app or online tool is easier to use.",
  "h1": "Apps and tools people can use without help.",
  "lede": "We design the screens of apps, customer portals and online tools, then test them with real people so confusing parts are fixed before launch.",
  "q": "What is UX design?",
  "a": "UX stands for user experience. UX design is making a digital product easy and pleasant to use: clear steps, sensible buttons and no dead ends. It relies on watching real people use the product and fixing what trips them up.",
  "ch_h": "Why good products lose users.",
  "ch_p": "Products often grow feature by feature until nobody can see the simple path through them. Users give up quietly.",
  "ch": ["New users don't know where to start", "Support gets the same questions every week", "Forms are long and people abandon them", "Each screen follows different rules"],
  "ov_h": "Watch, design, test, repeat.",
  "ov_p": "We begin by watching how people use your product today. Then we redesign the key journeys, test the new screens with real users and refine them.",
  "ov_note": "Testing with even a handful of real users usually reveals the biggest problems quickly.",
  "benefits": ["Fewer support requests", "More people finish sign-up and checkout", "Faster development with a clear design system", "Decisions based on what users actually do"],
  "deliver": ["Review of your current product", "Interviews or short user sessions", "User journey maps", "Wireframes for key screens", "Interface design for web or mobile", "Clickable prototype", "Usability testing with real people", "Design system and component library", "Developer hand-over notes"],
  "uses": ["Designing a new app from scratch", "Simplifying a sign-up or checkout flow", "Redesigning a customer portal", "Building an internal tool for staff", "Preparing a product for investors", "Creating a consistent design system"],
  "steps": [["Understand", "We review the product and talk to the people who use it."], ["Map", "We draw the main journeys and mark where people get stuck."], ["Design", "New screens are designed and turned into a clickable prototype."], ["Test", "Real users try the prototype while we watch and take notes."], ["Refine", "We fix what didn't work and prepare files for your developers."]],
  "tools": [["Design", ["Figma"]], ["Research", ["Video calls", "Screen recording"]], ["Hand-over", ["Figma Dev Mode"]]],
  "faq": [["Do you build the app as well?", "We focus on design and testing. We can work alongside your developers or suggest a team to build it."], ["How many people do you test with?", "It depends on the project. We agree the number and type of testers in the plan."], ["Can you work on part of a product?", "Yes. Many projects focus on one journey, such as sign-up or checkout."]],
  "related": ["website-design", "brand-identity", "website-development"],
  "cta_h": "Find out where users get stuck.",
  "cta_p": "Show us your app or tool. We'll suggest which journey to improve first.",
 },
 {
  "slug": "seo-content",
  "name": "SEO and content",
  "menu": "Help people find you on search",
  "line": "Clear page writing, tidy technical setup and honest monthly reports on what people search for and find.",
  "title": "SEO and Content Services | Pages Google Can Read | Unimind",
  "desc": "SEO and content from Unimind Studios: clear writing, tidy technical setup and honest monthly reports that help search engines and AI tools read your pages.",
  "h1": "Help people find you when they search.",
  "lede": "We make your pages easy for search engines and AI assistants to understand, write content that answers real questions, and report results in plain English.",
  "q": "What is SEO?",
  "a": "SEO stands for search engine optimisation. It is the work that helps search engines like Google understand your pages and show them to people searching for what you offer. It includes clear writing, a fast and tidy website, and earning links from other trusted sites.",
  "ch_h": "Why good businesses stay invisible.",
  "ch_p": "Search engines can only rank what they can read and understand. Many sites hide their best answers behind vague headings and slow pages.",
  "ch": ["Pages don't match what people actually search for", "Titles and descriptions are missing or repeated", "The site is slow or hard for Google to read", "Nobody reports what changed or why"],
  "ov_h": "Clear answers, tidy foundations, honest reports.",
  "ov_p": "We fix the technical basics first, then improve and write pages that answer the questions your customers search. We also make answers easy for AI assistants to quote.",
  "ov_note": "No one can promise a ranking position. We focus on the work that makes ranking possible and show you what changes.",
  "benefits": ["Pages that match real searches", "Better chances of appearing in AI answers", "A site Google can read easily", "Plain-English monthly reports"],
  "deliver": ["Technical SEO check-up", "Keyword and question research", "Page titles and descriptions", "Structured data (labels search engines read)", "Content plan for the next months", "New and improved page writing", "Internal links between related pages", "Google Search Console setup", "Monthly report in plain English"],
  "uses": ["Launching a new website", "Recovering after a site move", "Growing local enquiries", "Writing answer-first service pages", "Building a library of helpful articles", "Preparing for AI search tools"],
  "steps": [["Check", "We review how search engines see your site today and what is holding it back."], ["Research", "We find the words and questions your customers actually use."], ["Fix", "Technical issues, titles, descriptions and structure are put right."], ["Write", "We improve key pages and add new content to a shared plan."], ["Report", "Each month you see what changed, what worked and what comes next."]],
  "tools": [["Measure", ["Google Search Console", "Google Analytics"]], ["Check", ["Lighthouse", "Schema validators"]], ["Write", ["Google Docs"]]],
  "faq": [["How long until we see results?", "SEO usually takes months rather than weeks, and it depends on your field and competition. We show progress each month so you can judge for yourself."], ["Do you guarantee first place on Google?", "No. Google decides rankings, so any guarantee would be dishonest. We focus on the work that gives your pages the best chance."], ["What are AEO and GEO?", "AEO means answer engine optimisation and GEO means generative engine optimisation. Both are about making your content easy for AI assistants and answer boxes to understand and quote."]],
  "related": ["website-development", "website-design", "website-care"],
  "cta_h": "Find out what search engines see.",
  "cta_p": "Share your website address. We'll tell you the first things worth fixing.",
 },
 {
  "slug": "website-care",
  "name": "Website care",
  "menu": "Updates, fixes and monthly reports",
  "line": "Security updates, backups, small edits and a short report each month, so your site keeps working.",
  "title": "Website Care Plans | Updates, Backups and Fixes | Unimind",
  "desc": "Website care from Unimind Studios: security updates, backups, uptime checks, small edits and a plain-English monthly report so your website keeps working.",
  "h1": "Keep your website safe, fast and up to date.",
  "lede": "A monthly plan that handles updates, backups and small changes, with a short report so you always know the state of your site.",
  "q": "What is website care?",
  "a": "Website care is ongoing upkeep for a site that is already live. It covers software updates, security, backups, checking the site stays online and making small content changes, so problems are caught early instead of after something breaks.",
  "ch_h": "Why websites quietly decay.",
  "ch_p": "A site that nobody looks after slowly gets slower, less secure and out of date. Problems often appear at the worst moment.",
  "ch": ["Plug-ins and themes go months without updates", "There is no recent backup if something breaks", "Small text changes wait weeks", "Nobody notices when a form stops working"],
  "ov_h": "Small, regular care instead of big repairs.",
  "ov_p": "We check, update and back up your site on a set schedule, handle small edits from your team and send a short report every month.",
  "ov_note": "Care plans work best for sites we built, but we can take over sites built by others after a check-up.",
  "benefits": ["Lower risk of hacks and outages", "A recent backup is always ready", "Quick turnaround on small edits", "A clear monthly picture of your site"],
  "deliver": ["Software and plug-in updates", "Regular off-site backups", "Uptime monitoring", "Security checks", "Form and link testing", "A set number of edit hours each month", "Speed checks", "Monthly plain-English report"],
  "uses": ["After a new site launches", "Taking over a site from another developer", "Sites that change prices or news often", "Online shops that can't afford downtime", "Teams without an in-house developer", "Keeping SEO foundations in good shape"],
  "steps": [["Check-up", "We review your site, its hosting and any risks before taking it on."], ["Set up", "Backups, monitoring and an update schedule are put in place."], ["Look after", "We update, test and make small edits each month."], ["Report", "A short monthly report shows what we did and anything to watch."]],
  "tools": [["Monitoring", ["Uptime checks", "Search Console"]], ["Safety", ["Off-site backups", "Security scans"]], ["Speed", ["Lighthouse"]]],
  "faq": [["Can you look after a site you didn't build?", "Yes, after a check-up. We first review the site so we know what we're taking on and can flag any risks."], ["What happens to unused edit hours?", "This depends on the plan you choose and is written in the agreement."], ["Can we cancel the plan?", "The notice period is set out in the agreement. We make sure you have all files and logins if you leave."]],
  "related": ["website-development", "seo-content", "website-design"],
  "cta_h": "Stop worrying about your website.",
  "cta_p": "Tell us where your site is hosted and what it runs on. We'll suggest the right level of care.",
 },
]

HOME_FAQ = [
 ["What does Unimind Studios do?", "We design and build brands, websites and digital products. That covers the logo and look of your business, the website itself, the code behind it, and the work that helps people find it on Google."],
 ["How long does a new website take?", "It depends on how many pages you need and how ready your content is. After our first meeting we send a written timeline with dates for each stage, so you know what happens when before any work starts."],
 ["Can you guarantee we will rank first on Google?", "No. Nobody can honestly promise that, because Google decides rankings. What we can do is build pages that are fast, clearly written and easy for search engines to read, then show you exactly what changed each month."],
 ["Can you improve our current website instead of starting over?", "Yes. We start with a review of what you have. Sometimes a few fixed pages and a faster setup are enough. If a rebuild makes more sense, we explain why in plain terms."],
 ["Who owns the website when it is finished?", "You do. At the end of the project we hand over the files, the logins and the source code, which is the underlying text that makes the site work."],
 ["How do we get started?", "Book a meeting using the Book Meeting button. We ask about your business, your customers and what is not working today. Then we send a written plan and a quote."],
]

SERVICES_FAQ = [
 ["Can we hire you for just one service?", "Yes. Every service stands on its own. Many clients start with one, such as a brand refresh, and add others later."],
 ["How do you price projects?", "Each project is quoted after a first meeting, based on the pages, features and timeline you need. The quote lists exactly what is included."],
 ["Do you work with businesses outside our city?", "Yes. We run meetings, reviews and hand-overs online, so location doesn't limit who we can work with."],
]

CONTACT_FAQ = [
 ["What happens after I send the form?", "We read every message and reply by email, usually with a few questions or a suggested time for a meeting."],
 ["Is the first meeting free?", "Yes. The first meeting is for understanding your needs. There's no charge and no obligation."],
 ["What should I prepare?", "Your website address if you have one, a rough idea of what you need and any deadline. That's enough to start."],
]

GLOSSARY = [
 ["Brand", [
  ["Brand identity", "The visible parts of a brand, such as logo, colours, fonts and images, that make a business recognisable."],
  ["Brand guidelines", "A short document explaining how to use the logo, colours, fonts and tone of voice correctly."],
  ["Tone of voice", "The personality in a brand's writing, for example friendly and plain, or formal and precise."],
  ["Logo lockup", "A fixed arrangement of a logo's symbol and name, such as side by side or stacked."],
 ]],
 ["Design", [
  ["UX (user experience)", "How easy and pleasant a website or app is to use, from first visit to finished task."],
  ["UI (user interface)", "The screens, buttons, menus and forms a person sees and touches."],
  ["Wireframe", "A simple sketch of a page that shows what goes where, without colours or images."],
  ["Prototype", "A clickable model of a website or app used to test ideas before building."],
  ["Responsive design", "A layout that rearranges itself to fit phones, tablets and computers."],
  ["Accessibility", "Designing so people with disabilities, including those using screen readers or keyboards, can use a site."],
 ]],
 ["Build", [
  ["CMS (content management system)", "Software such as WordPress that lets you edit website pages without writing code."],
  ["Domain name", "Your website's address, for example yourcompany.com."],
  ["Hosting", "The rented computer space where your website's files live so people can visit them."],
  ["SSL certificate", "A security file that encrypts traffic and shows the padlock and https in the browser."],
  ["Core Web Vitals", "Google's measures of how fast a page loads, how quickly it responds and how stable it looks while loading."],
  ["Redirect", "A rule that sends visitors and search engines from an old web address to a new one."],
 ]],
 ["Search and measurement", [
  ["SEO (search engine optimisation)", "Work that helps search engines understand your pages and show them to the right people."],
  ["AEO (answer engine optimisation)", "Writing and structuring content so answer boxes and voice assistants can quote it directly."],
  ["GEO (generative engine optimisation)", "Making content easy for AI tools such as chat assistants to understand, trust and cite."],
  ["Keyword", "A word or phrase people type into a search engine."],
  ["Meta description", "A short summary of a page that search engines may show under the page title in results."],
  ["Structured data", "Hidden labels in a page's code that tell search engines exactly what the page contains."],
  ["Google Search Console", "A free Google tool that shows how your site appears in search and flags problems."],
  ["Google Analytics (GA4)", "A free Google tool that shows how many people visit your site and what they do there."],
 ]],
]

WORK_FAQ = [
 ["Are these real results?", "Yes. Every figure on this page comes from the client's own Google Search Console or ads dashboard, and the screenshots are inside each case study. Where we worked a number out ourselves, it is marked as calculated."],
 ["Can you get the same results for my business?", "We can't promise that. Results depend on your field, competition, budget and starting point. After a first meeting we'll tell you honestly what looks realistic."],
 ["Which services do these projects cover?", "The case studies cover SEO, Google Ads and Meta Ads. The portfolio shows websites, social post designs and AI-assisted graphic design."],
]
